#   _____ _               _  ______          _            _
#  /  __ \ |             | | | ___ \        | |          | |
#  | /  \/ |__   ___  ___| |_| |_/ / __ ___ | |_ ___  ___| |_
#  | |   | '_ \ / _ \/ __| __|  __/ '__/ _ \| __/ _ \/ __| __|
#  | \__/\ | | |  __/\__ \ |_| |  | | | (_) | ||  __/ (__| |_
#   \____/_| |_|\___||___/\__\_|  |_|  \___/ \__\___|\___|\__|
#
# Resource page: https://www.spigotmc.org/resources/53494
# Discord: https://discord.gg/B4MAJVk
#
# If you encounter any issues, please report them
# to discord support server or via pm.
# Bugs or problems are usually fixed within a few hours.
# You can ignore the IDs in some setting names (_<ID>).
#
#################################################################
# Blocks and entities, which should be able to become protected, #
# can be found in protectables.yml                              #
#################################################################

general:
  # Default: English (en-US) - no download required.
  # This defines the default language. You can place multiple locales in the plugin's "Language" folder to display different locales depending on the player's locale.
  # You can access translations maintained by the community in our Discord: https://discord.gg/B4MAJVk
  # To access translations, other than en-US, execute /translations in the Discord server.
  language: 'en-US'

  # Worlds where players should
  # be able to lock objects
  worlds_list:
    - world

  # Set the format of all economy related displays.
  # Info: https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html
  # NOTE: This setting requires server reload / restart.
  eco-format:
    normal: '$#,##0.00'
    # The short format will use the normal format if the value is lower than 1000.
    # If the value is higher or equal than 1000, it will return {value} divided by 1000.
    # This format is only used by a small amount of messages.
    short: '${value}k'

  # If enabled, limit permissions will be combined instead of just taking the highest value.
  # Example: A player has the permission chestprotect.blocks.5 and chestprotect.blocks.2.
  #          If enabled: This will result in a limit of 7 protected blocks (containers etc.).
  #          If disabled: This will result in a limit of 5 protected blocks (containers etc.).
  permission-stacking: false


#################################################################
# Blocks and entities, which should be able to become protected, #
# can be found in protectables.yml                              #
#################################################################


# Protection settings
# Protection costs and protection types can be edited in protectables.yml
protection:
  # Should protections take damage from tnt explosion to get unlocked?
  allow-tnt: false

  # Sound settings
  # You can disable sounds by setting them to ''
  sound:
    # Played when protection has been created.
    locked_sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    # Played on protection deletion.
    unlocked_sound: 'BLOCK_ANVIL_BREAK'

  # Default protection settings
  setting:
    # Accept redstone signals?
    redstone:
      enabled_11: false

  # Teleport to protection through the menu.
  # Permission chestprotect.teleport
  teleportation:
    # Wait x seconds before starting teleportation.
    wait: 3
    # Set teleportation cost.
    cost: 200


# General Teleportation Settings
# Command specific teleportation options can be find in their sections.
teleport:
  # General teleportation cost. Some features might have specific options, which override this.
  costs: 0
  # Set the cost of any teleportation to 0 for players that joined the server for the first time.
  # You can define a time span here. Example: 1d = players that joined the server 23 hours ago, won't pay for any teleportation.
  first-join_time: 0h
  # Wait-time
  # Timeunit: seconds
  wait: 3

# Player default settings
player:
  # Here you can set DEFAULT settings for NEW players.
  # The players will be able to change these settings later in the GUI, if they have permission to do so.
  # NOTE: These settings are default settings. That means that they will only apply for new players.
  setting:
    # Make the command lock and unlock persistent?
    persistent_lock:
      # Default value
      default: false
    # Make the command trust, untrust and setrole persistent?
    persistent_trust:
      default_3: false
    # Auto lock placed blocks, which are protectable?
    auto_lock:
      default_5: true
    # Send notification when opening a protection?
    notifications:
      default_14: true


# Database settings
database:
  # MySQL database
  # To use this without issues, your connection limits etc. need to be configured properly in your MySQL server configuration.
  # It is not recommended connecting multiple instances of ChestProtect servers to one database with the same table prefix.
  mysql:
    # NOTE: If disabled, SQLite will be used instead.
    enabled_20: false
    ip-address: 'localhost'
    port: '3306'
    username: 'minecraft'
    password: 'password'
    database: 'chestprotect'

    # It is highly recommended setting a unique table prefix if the plugin shares a database with other plugins or ChestProtect instances.
    table-prefix: 'chestprotect_'

  # Database purger
  # Delete protections from
  # inactive players
  inactive-player-deleter:
    # NOTE: This setting requires server reload.
    enabled: true
    # Time in days how long players have to be offline to be marked as inactive.
    offline-days: 120

# Events options
event:
  # If a player opens a protected object.
  open-protection:
    # Should players be able to open their double doors by just clicking at only one door?
    # This also includes iron double, iron single and iron trap doors.
    double-doors: true

  # If someone places a protectable block or armor-stand, which did not get auto locked.
  block-place:
    # This message will only appear if the player can protect objects at his location.
    # For example, if he is in a WorldGuard region and is not allowed to create protection there, the message will not be displayed.
    notify: true



command:
  # Command shortcuts
  # NOTE: These settings require server reload.
  shortcut:
    # Enable /chestprotect lock shortcut: /Lock
    # Set this to false, if you don't want this.
    lock: true
    # Enable /chestprotect lock shortcut: /Unlock
    unlock: true
    # Enable /chestprotect lock shortcut: /Trust
    trust: true
    # Enable /chestprotect lock shortcut: /Untrust
    untrust: true
    # Enable /chestprotect setrole shortcut: /SetRole
    setrole: true

  # Set aliases for the /chestprotect command
  # NOTE: This setting requires server reload.
  alias:
    chestprotect_list: [ ]



# ChestProtect menu settings (/chestprotect menu)
gui:
  # Should ChestProtect automatically adjust the length of item lore lines?
  # Recommended length is 35.
  # NOTE: Set this to 0 to disable it.
  max-lore-length: 0



# Integrations settings
integration:
  # Supports: Lands (https://www.spigotmc.org/resources/53313), SuperiorSkyblock2, BentoBox, PlotSquared, WorldGuard
  # If you want to allow protections being opened during wars, add the "CHESTPROTECT_OPEN" flag to the wars.yml configuration file of Lands.
  lands:
    # Should protections only be allowed inside claims?
    # Protections in the wilderness won't be allowed.
    # This also means that protections inside a land will get unlocked, if the land gets unclaimed.
    only-land: false
    # If the location is claimed, should it only be allowed if the player is trusted in that claim?
    only-trusted_2: false
    # Should protections inside a land/area get unlocked, if the player gets untrusted at this land/area?
    # This includes the expiration of rentals.
    untrust-remove: false
    # Supports: Lands (https://www.spigotmc.org/resources/53313), SuperiorSkyblock2, BentoBox, PlotSquared, WorldGuard
    # Allow players, which are trusted in the region where the farm is located in, to break blocks, place blocks and interact, if they're allowed to do so in the region?
    # This is a default option. Players can change it later in the menu.
    allow-region-members: false
    # Allow region owners to unlock protections of other players?
    # This also allows owners, to open protections of other players in their claim.
    owner-unlock: false

  # chestprotect-lock flag that allows you to prevent locking objects in plugins like WorldGuard.
  flag:
    # Apply the chestprotect-lock flag also to global regions in world manager plugins, like WorldGuard?
    # For Lands use /lands admin wilderness instead.
    # This option requires server reload / restart.
    global-regions: false
    # Default state of the lock flag. If you use ProtectionStones, then you might want to set this to true.
    default-state: false

  # Economy settings
  # If all types are disabled, the item based economy will be used instead.
  economy:
    Vault:
      # You need an economy plugin, which supports Vault, to let this work.
      enabled_9: true
      # Server bank account name. Player expenses will go here. Empty means, that this feature is disabled.
      server-bank: ''
    levels:
      enabled_10: false
    # Item currency is used when all other economy options are disabled or unavailable.
    # The currency item can be edited in the GUI language file at the "currency" item.
    items:
      # If enabled, only items that have the same name, lore etc. will belong to the currency.
      # Not just items of the same type or items with the same model-data.
      strict: false

  # Chat integrations
  chat:
    # PlaceholderAPI
    PlaceholderAPI:
      enabled_6: true

  # Web integrations
  web:
    # Dynmap
    Dynmap:
      enabled_8: false
      # The name of the layer where users can see the marked protections.
      layer: 'ChestProtect'
      icon: 'Protections X: {x} Z: {z}'
