name: ChestProtect
main: me.angeschossen.chestprotect.ChestProtect
version: ${project.version}
author: Angeschossen
api-version: 1.13
folia-supported: true

softdepend: [Lands, UpgradeableHoppers, BetterFarming, UpradeableSpawners, PlaceholderAPI, Vault, WorldGuard, BentoBox, PlotSquared, SuperiorSkyblock2, DecentHolograms, HolographicDisplays, CMI]

commands:
  chestprotect:
    aliases: [cp, protect, protection]
    description: Protect objectives
  lock:
    aliases: [lo]
    description: Lock objects
  unlock:
    aliases: [ul]
    description: Unlock objects
  trust:
    aliases: [tr]
    description: Trust player to objective
  untrust:
    aliases: [ut]
    description: Untrust player from objective

permissions:
  chestprotect.*:
    description: Gives access to all ChestProtect actions
    default: op
    children:
      chestprotect.blocks.<number>:
        description: Set maximum block protections amount
        default: op
      chestprotect.entities.<number>:
        description: Set maximum entity protections amount
        default: op
      chestprotect.members.<number>:
        description: Set maximum protection member amount
        default: op
      chestprotect.groups.<number>:
        description: Set maximum groups amount
        default: op
      chestprotect.free.blocks.<number>:
        description: <number> block protections are free (don't cost anything)
        default: op
      chestprotect.free.entities.<number>:
        description: <number> entity protections are free (don't cost anything)
        default: op
      chestprotect.command.*:
        description: Get access to all commands
        default: op
        children:
          chestprotect.command.exit:
            description: Exit /Lock, /Unlock, /Untrust, /Trust, /SetRole mode
            default: op
          chestprotect.command.help:
            description: Get command information, help
            default: op
          chestprotect.command.lock:
            description: Enter /Lock mode
            default: op
          chestprotect.command.unlock:
            description: Enter /Unlock mode
            default: op
          chestprotect.command.trust:
            description: Enter /Trust mode
            default: op
          chestprotect.command.untrust:
            description: Enter /Untrust mode
            default: op
          chestprotect.command.setrole:
            description: Enter /SetRole mode
            default: op
          chestprotect.command.view:
            description: View nearby protections
            default: op
      chestprotect.bypass.*:
        description: Bypass all protections
        default: op
        children:
          chestprotect.bypass.open:
            description: Open other players protections
            default: op
          chestprotect.bypass.unlock:
            description: Unlock other players protections
            default: op
      chestprotect.setting.*:
        description: Access to all protection and player settings
        default: op
        children:
          chestprotect.setting.player.*:
            description: Access to all player settings
            default: op
            children:
              chestprotect.setting.player.lock_persistent:
                description: Access to toggle lock persistent setting
                default: op
              chestprotect.setting.player.unlock_persistent:
                description: Access to toggle unlock persistent setting
                default: op
              chestprotect.setting.player.trust_persistent:
                description: Access to toggle trust persistent setting
                default: op
              chestprotect.setting.player.untrust_persistent:
                description: Access to toggle untrust persistent setting
                default: op
              chestprotect.setting.player.setrole_persistent:
                description: Access to toggle setrole persistent setting
                default: op
              chestprotect.setting.player_trust:
                description: Access to toggle role player trust setting
                default: op
              chestprotect.setting.player_untrust:
                description: Access to toggle role player untrust setting
                default: op
              chestprotect.setting.player_setrole:
                description: Access to toggle role player setrole setting
                default: op
      chestprotect.admin.*:
        description: Access to all admin actions and commands
        default: op
        children:
          chestprotect.admin.edit:
            description: Edit other players protections
            default: op
          chestprotect.admin.command.*:
            description: Access to all admin commands
            default: op
          chestprotect.admin.priority:
            description: Bypass role priorities
            default: op
          chestprotect.admin.command.player:
            description: Access to /Protect admin player command
            default: op
            children:
              chestprotect.admin.command.player.delete:
                description: Access to /Protect admin player <player> delete command
                default: op
          chestprotect.admin.command.import:
            descriptionw: Import other plugins protections. /Protect admin import lwc
            default: op
      chestprotect.teleport:
        description: Teleport to protection via the GUI menu.
        default: op
