#   _____ _               _  ______          _            _
#  /  __ \ |             | | | ___ \        | |          | |
#  | /  \/ |__   ___  ___| |_| |_/ / __ ___ | |_ ___  ___| |_
#  | |   | '_ \ / _ \/ __| __|  __/ '__/ _ \| __/ _ \/ __| __|
#  | \__/\ | | |  __/\__ \ |_| |  | | | (_) | ||  __/ (__| |_
#   \____/_| |_|\___||___/\__\_|  |_|  \___/ \__\___|\___|\__|
#
# Resource page: https://www.spigotmc.org/resources/53494
# Discord: https://discord.gg/B4MAJVk
#
# If you encounter any issues, please report them
# to discord support server or via pm.
# Bugs or problems are usually fixed within a few hours.
# You can ignore the IDs in some setting names (_<ID>).
#
#################################################################
# Blocks and entities, wich should be able to become protected, #
# can be found in protectables.yml                              #
#################################################################

general:
  # Language
  # PRE translated:
  # English: en-US
  # German: de-DE by Cryper96
  # Chinese: zh-CN
  # Polish: pl-PL
  # French: fr-FR by Nogapra
  language: 'en-US'

  # Worlds where players should
  # be able to lock objects
  worlds_list:
    - world

  # Set the format of all economy related displays.
  # NOTE: This setting requires server reload / restart.
  eco-format: '#,##0.00'


#################################################################
# Blocks and entities, wich should be able to become protected, #
# can be found in protectables.yml                              #
#################################################################


# Protection settings
protection:
  # Costs to create protection
  costs:
    general: 50
    # Increase protection cost by a specific percentage. To disable this, use 0.
    # For example paying 5% more compared to the previous protection creation (lock).
    increase: 5.0
    # Give players a percentage back of the original lock cost. Gived at unlock. To disable this, use 0.
    cashback: 50.0

  # Should protections take damage from tnt explosion to get unlocked?
  allow-tnt: false

  # Sound settings
  # You can disable sounds by setting them to ''
  sound:
    # Played when protection has been created.
    locked_sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    # Played on protection deletion.
    unlocked_sound: 'BLOCK_ANVIL_BREAK'

  # Default protection settings
  setting:
    # Accept redstone signals?
    redstone:
      enabled_11: false

  # Teleport to protection through the menu.
  # Permission chestprotect.teleport
  teleportation:
    # Wait x seconds before starting teleportation.
    wait: 3
    # Set teleportation cost.
    cost: 200

  # Role DEFAULT settings
  # These can be changed in the GUI.
  # NOTE: These settings are default settings. That means that they will only apply for new protections.
  role:
    # Visitors (untrusted players)
    visitor:
      # Settings
      setting:
        # Allow this role to get items out of the protection by using a hopper?
        # NOTE: It's recommended to let this disabled for this role.
        hopper_transfer:
          default_16: false

      management:
        # Allow this role to trust players?
        # /ChestProtect trust
        # NOTE: It's recommended to let this disabled for this role.
        player_trust:
          default_6: false
        # Allow this role to untrust players?
        # /ChestProtect untrust
        # NOTE: It's recommended to let this disabled for this role.
        player_untrust:
          default_7: false
        # Allow this role to set roles?
        # /Protect setrole
        # NOTE: It's recommended to let this disabled for this role.
        player_setrole:
          default_11: false

    # Members (trusted players)
    member:
      setting:
        # Allow this role to get items out of the protection by using a hopper?
        hopper_transfer:
          default_17: true
      management:
        # Allow this role to trust players?
        # /ChestProtect trust
        player_trust:
          default_8: false
        # Allow this role to untrust players?
        # /ChestProtect untrust
        player_untrust:
          default_15: false
        # Allow this role to set roles?
        # /Protect setrole
        player_setrole:
          default_12: false

    # Admins (role that can be set; NOT server admin)
    admin:
      setting:
        # Allow this role to get items out of the protection by using a hopper?
        hopper_transfer:
          default_18: true

      management:
        # Allow this role to trust players?
        # /ChestProtect trust
        player_trust:
          default_9: true
        # Allow this role to untrust players?
        # /ChestProtect untrust
        player_untrust:
          default_10: true
        # Allow this role to set roles?
        # /Protect setrole
        player_setrole:
          default_13: true


# Player default settings
player:
  # Here you can set DEFAULT settings for NEW players.
  # The players will be able to change these settings later in the GUI, if they have permission to do so.
  # NOTE: These settings are default settings. That means that they will only apply for new players.
  setting:
    # Make the command lock and unlock persistent?
    persistent_lock:
      # Default value
      default: false
    # Make the command trust, untrust and setrole persistent?
    persistent_trust:
      default_3: false
    # Auto lock placed blocks, wich are protectable?
    auto_lock:
      default_5: true
    # Send notification when opening a protection?
    notifications:
      default_14: true


# Database settings
database:
  # MySQL database
  # To use this without issues, your connection limits etc. need to be configured properly in your MySQL server configuration.
  # It is not recommended connecting multiple instances of ChestProtect servers to one database with the same table prefix.
  mysql:
    # NOTE: If disabled, SQLite will be used instead.
    enabled_20: false
    ip-address: 'localhost'
    port: '3306'
    username: 'minecraft'
    password: 'password'
    database: 'chestprotect'

    # It is highly recommended setting a unique table prefix if the plugin shares a database with other plugins or ChestProtect instances.
    table-prefix: 'chestprotect_'

  # Database purger
  # Delete protections from
  # inactive players
  inactive-player-deleter:
    # NOTE: This setting requires server reload.
    enabled: true
    # Time in days how long players have to be offline to be marked as inactive.
    offline-days: 120

# Events options
event:
  # If a player opens a protected object.
  open-protection:
    # Should players be able to open their double doors by just clicking at only one door?
    # This also includes iron double and single doors.
    double-doors: true

  # If someone places a protectable block or armorstand, which did not get auto locked.
  block-place:
    # This message will only appear if the player can protect objects at his location.
    # For example, if he is in a WorldGuard region and is not allowed to create protection there, the message will not be displayed.
    notify: true



command:
  # Command shortcuts
  # NOTE: These settings require server reload.
  shortcut:
    # Enable /ChestProtect lock shortcut: /Lock
    # Set this to false, if you don't want this.
    lock: true
    # Enable /ChestProtect lock shortcut: /Unlock
    unlock: true
    # Enable /ChestProtect lock shortcut: /Trust
    trust: true
    # Enable /ChestProtect lock shortcut: /Untrust
    untrust: true
    # Enable /ChestProtect setrole shortcut: /SetRole
    setrole: true

  # Set aliases for the /ChestProtect command
  # NOTE: This setting requires server reload.
  alias:
    chestprotect_list: [ ]



# ChestProtect menu settings (/ChestProtect menu)
gui:
  # Should ChestProtect automatically adjust the length of item lore lines?
  # Recommended length is 35.
  # NOTE: Set this to 0 to disable it.
  max-lore-length: 0



# Integrations settings
integration:
  # Lands settings (https://www.spigotmc.org/resources/53313)
  # If you want to allow protections being opened during wars, add the "CHESTPROTECT_OPEN" flag to the wars.yml configuration file of Lands.
  lands:
    # Should protections only be allowed inside claims, where they're trusted?
    # Protections in the wilderness won't be allowed.
    # This also means that protections inside a land will get unlocked, if the land gets unclaimed.
    only-trusted: false
    # Should protections inside of a land/area get unlocked, if the player gets untrusted at this land/area?
    # This includes the expiration of rentals.
    untrust-remove: false
    # Allow players, which are trusted in the region where the protection is located in, to open the protection?
    # Supports: Lands (https://www.spigotmc.org/resources/53313), SuperiorSkyblock2, BentoBox, PlotSquared, WorldGuard
    allow-region-members: false
    # Allow region owners to unclock protections of other players?
    # Supports: Lands (https://www.spigotmc.org/resources/53313), SuperiorSkyblock2, BentoBox, PlotSquared, WorldGuard
    owner-unlock: false

  # Economy settings
  # If no Vault is disabled or no economy plugin is found, it will use the "currency" item from the gui file instead.
  economy:
    # Vault
    # You need an economy plugin, which supports Vault, to let this work.
    Vault:
      enabled_10: true

    levels:
      enabled_9: false

  # Chat integrations
  chat:
    # PlaceholderAPI
    PlaceholderAPI:
      enabled_6: true

  # Web integrations
  web:
    # Dynmap
    Dynmap:
      enabled_8: false
      # The name of the layer where users can see the marked protections.
      layer: 'ChestProtect'
      icon: 'Protections X: {x} Z: {z}'
