#   _____ _               _  ______          _            _
#  /  __ \ |             | | | ___ \        | |          | |
#  | /  \/ |__   ___  ___| |_| |_/ / __ ___ | |_ ___  ___| |_
#  | |   | '_ \ / _ \/ __| __|  __/ '__/ _ \| __/ _ \/ __| __|
#  | \__/\ | | |  __/\__ \ |_| |  | | | (_) | ||  __/ (__| |_
#   \____/_| |_|\___||___/\__\_|  |_|  \___/ \__\___|\___|\__|
#
# Resource page: https://www.spigotmc.org/resources/53494
# Discord: https://discord.gg/B4MAJVk

# If you encounter any issues, please report them
# to discord support server or via pm.
# Bugs or problems are usually fixed within a few hours.
# You can ignore the IDs in some setting names (_<ID>).

general:
  # Language
  # PRE translated:
  # English: en-US
  # Chinese: zh-CN
  # Polish: pl-PL
  # French: fr-FR
  language: 'en-US'
  # Should ChestProtect check for updates? It will only send a notification to console.
  check-update: true

  # Worlds where players should
  # be able to lock objects
  worlds_list:
    - world

  # Date format
  # MM: Month
  # dd: Day of month
  # yyyy: Year
  # hh: hours
  # mm: minutes
  # ss: seconds
  # NOTE: These settings require server reload.
  dateFormat:
    # General format for invities etc.
    # 24 hour format:
    # MM/dd/yyyy HH:mm:ss
    general_2: 'MM/dd/yyyy hh:mm:ss'
    # Format for things like cooldown etc.
    # NOTE: You will need to change
    # the messages to for example {time} hours,
    # if you change the format to
    # 'hh:mm:ss'.
    small: 'mm:ss'



# Blocks and entities, wich should be able to become protected.
# NOTE: Only interactable blocks and entities can be protected.
protectables:
  types:
    - CHEST
    - BARREL
    - FURNACE
    - BLAST_FURNACE
    - SMOKER
    - OAK_DOOR
    - IRON_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - OAK_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - BIRCH_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - ACACIA_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    - ARMOR_STAND
    - COW
    - SHEEP
    - PIG
    - CHICKEN

  # Allow protecting NPCs?
  npc: false



# Protection settings
protection:
  # Costs to create protection
  costs:
    general: 50
    # Increase by protection amount
    # NOTE: Percentage (For example putting 10% per protection on top of the normal lock price per claim.)
    increase: 5
    # Give players money back, if they unlock an object?
    cashback: 10

  # Sound settings
  sound:
    # Played when protection has been created.
    locked: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    # Played on protection deletion.
    unlocked: 'BLOCK_ANVIL_BREAK'

  # Default protection settings
  setting:
    # Ignore redstone signals?
    redstone_ignore:
      enabled_10: false

  # Should all members of a protection be displayed in one GUI, no matter what role they have?
  roles-mixed: true

  # Role DEFAULT settings
  # These can be changed in the GUI.
  # NOTE: These settings are default settings. That means that they will only apply for new protections.
  role:
    # Visitors (untrusted players)
    visitor:
      # Settings
      setting:
        # Allow this role to trust players?
        # /ChestProtect trust
        # NOTE: It's recommended to let this disabled for this role.
        player_trust:
          default_6: false
        # Allow this role to untrust players?
        # /ChestProtect untrust
        # NOTE: It's recommended to let this disabled for this role.
        player_untrust:
          default_7: false
        # Allow this role to set roles?
        # /Protect setrole
        # NOTE: It's recommended to let this disabled for this role.
        player_set_role:
          default_11: false
        # Allow this role to get items out of the protection by using a hopper?
        # NOTE: It's recommended to let this disabled for this role.
        hopper_transfer:
          default_16: false

    # Members (trusted players)
    member:
      setting:
        # Allow this role to trust players?
        # /ChestProtect trust
        player_trust:
          default_8: false
        # Allow this role to untrust players?
        # /ChestProtect untrust
        player_untrust:
          default_15: false
        # Allow this role to set roles?
        # /Protect setrole
        player_set_role:
          default_12: false
        # Allow this role to get items out of the protection by using a hopper?
        hopper_transfer:
          default_17: false

    # Admins (role that can be set; NOT server admin)
    admin:
      setting:
        # Allow this role to trust players?
        # /ChestProtect trust
        player_trust:
          default_9: true
        # Allow this role to untrust players?
        # /ChestProtect untrust
        player_untrust:
          default_10: true
        # Allow this role to set roles?
        # /Protect setrole
        player_set_role:
          default_13: false
        # Allow this role to get items out of the protection by using a hopper?
        hopper_transfer:
          default_18: false



# Player default settings
player:
  # Here you can set DEFAULT settings for NEW players.
  # The players will be able to change these settings later in the GUI, if they have permission to do so.
  # NOTE: These settings are default settings. That means that they will only apply for new players.
  setting:
    # Make the command /Lock persistent?
    lock_persistent:
      # Default value
      default: false
    # Make the command /Unlock persistent?
    unlock_persistent:
      default_2: false
    # Make the command /Trust persistent?
    trust_persistent:
      default_3: false
    # Make the command /Protect setRole persistent?
    set_role_persistent:
      default_14: false
    # Make the command /Untrust persistent?
    untrust_persistent:
      default_4: false
    # Auto lock placed blocks, wich are protectable?
    auto-lock:
      default_5: true



# Database settings
database:
  # Database purger
  # Delete protections from
  # inactive players
  inactive-player-deleter:
    # NOTE: This setting requires server reload.
    enabled: true
    # Time in days how long players have to be offline to be marked as inactive.
    offline-days: 120

# Events options
event:
  # If a player opens a protected object.
  open-protection:
    # Notficiations settings
    notify:
      # Should the owner of a protection get a message, if he opens it.
      owner: false
      # Should a member of a protection get a message, if he opens it.
      member: true
    # Should it be possible to open a locked iron door if the player is trusted at it?
    open-iron-doors: true

  # If someone places a protectable block or armorstand.
  block-place:
    # This message will only appear if the player can protect objects at his location.
    # For example, if he is in a WorldGuard region and is not allowed to create protection there, the message will not be displayed.
    notify: true



command:
  # Command shortcuts
  # NOTE: These settings require server reload.
  shortcut:
    # Enable /ChestProtect lock shortcut: /Lock
    # Set this to false, if you don't want this.
    lock: true
    # Enable /ChestProtect lock shortcut: /Unlock
    unlock: true
    # Enable /ChestProtect lock shortcut: /Trust
    trust: true
    # Enable /ChestProtect lock shortcut: /Untrust
    untrust: true
  # Set aliases for the /ChestProtect command
  # NOTE: This setting requires server reload.
  aliases_list:
    - protect
    - protection
    - lockable



# ChestProtect menu settings (/ChestProtect menu)
gui:
  # Should ChestProtect automatically adjust the length of item lore lines?
  # Recommended length is 35.
  # NOTE: Set this to 0 to disable it.
  max-lore-length: 0



# Integrations settings
integration:
  # Management integrations
  manager:
    # Lands
    # Link: https://www.spigotmc.org/resources/53313
    Lands:
      enabled_2: true
      # Should ChestProtect only allow protections in claims where they're trusted?
      only-claim: false
      # Should ChestProtect delete all protections of the deleted claim?
      remove-unclaim: false
      # Allow hopper transfer for all roles, if protection is in claim?
      hopper-transfer: true

    # Towny
    Towny:
      enabled_3: true
      # Should ChestProtect only allow protections in claims?
      only-claim_2: false
      # Should ChestProtect delete all protections of the deleted claim?
      remove-unclaim_2: false
      # Allow hopper transfer for all roles, if protection is in claim?
      hopper-transfer_2: true

    # Residence
    Residence:
      enabled_9: true
      # Should ChestProtect only allow protections in claims?
      only-claim_3: false
      # Should ChestProtect delete all protections of the deleted claim?
      remove-unclaim_3: false
      # Allow hopper transfer for all roles, if protection is in claim?
      hopper-transfer_3: true

  # Economy integrations
  economy:
    # Default currency
    # Used when no Vault Economy plugin found or Vault disabled.
    # NOTE: This currency is item based.
    default:
      # Item, wich should be used as currency.
      # Materials can be found here:
      # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
      item: 'DIAMOND'

    # Vault
    Vault:
      enabled_5: true

  # Chat integrations
  chat:
    # PlaceholderAPI
    PlaceholderAPI:
      enabled_6: true

  # Web integrations
  web:
    # Dynmap
    Dynmap:
      enabled_8: false
      # The name of the layer where users can see the marked protections.
      layer: 'ChestProtect'
      icon: 'Protections X: {x} Z: {z}'
